### ISSUE TITLE
How to write a function that uses a Container?

### ISSUE THREAD

**Issue by llogiq** [bluss/indexing#10]
The docs could use an example of using a `Container` in a function. For an easy example, let's say I want to build an indexed binary tree. With a simple `Vec` that would be:

```rust
struct Tree(Option<(usize, usize)>);

fn tree(c: &mut Vec<Tree>, depth: usize) -> usize { // return the root index
    if depth == 0 {
        c.push(Tree(None));
    } else {
        let left = tree(c, depth - 1);
        let right = tree(c, depth - 1);
        c.push(Tree(Some((left, right))));
    }
    c.len() - 1
}
```

However, if I try to convert this code to use a `Container`:

```rust
struct Tree<'id>(Option<(Index<'id>, Index<'id>)>);

fn tree<'a>(c: &mut Container<'a, &mut Vec<Tree<'a>>, OnlyIndex>, depth: usize) -> Index<'a> {
    if depth == 0 {
        c.push(Tree(None))
    } else {
        let left = tree(c, depth - 1);
        let right = tree(c, depth - 1);
        c.push(Tree(Some((left, right))))
    }
}

fn main() {
    let mut v = vec![];
    scope(&mut v, |v| {
        let mut v = v.only_index();
        tree(&mut v, 0);
    });
    assert_eq!(v.len(), 7);
}
```

I get a lifetime error:

```
34 |     let mut v = vec![];
   |         ----- borrowed data cannot be stored into here...
35 |     scope(&mut v, |v| {
   |                   --- ...because it cannot outlive this closure
36 |         let mut v = v.only_index();
   |                       ^^^^^^^^^^ cannot be stored outside of its closure

error: aborting due to previous error
```

It is likely that I've messed up some detail, but it is equally likely that someone else trying to implement this will, too. So adding an example that shows how to do it right might be valuable to prospective users.

**Comment by CAD97** [comment]
The problem here is that you're getting `v: Vec<Tree<'scope>>` in your main scope, which obviously exists outside the safe indexing scope, and so is illegal.

You'd need to transfer the vector into the scope to do this. Unfortunately, it seems that this doesn't work. (Tooting my own horn: it _should_ work in [indexing-str](https://crates.io/crates/indexing-str) once 0.2 adds mutability support.)

**Comment by llogiq** [comment]
Tooting *my* own horn, [compact_arena](https://github.com/llogiq/compact_arena) also allows this (as it can because the arena contents are guaranteed to be dropped when the arena is).

**Comment by bluss** [comment]
compact_arena is some next level stuff (literally), excited to see it and congratulations! :tada:  @llogiq

**Comment by llogiq** [comment]
Thank you! It took me some versions to get it in a sound state, and I couldn't have done it without awesome help by Ralf Jung and many others.
